config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'
  get 'show_user' => 'epicenter#show_user'
  get  'now_following' => 'epicenter#now_following'
  get 'unfollow' => 'epicenter#unfollow'
  get 'tag_tweets' => 'epicenter#tag_tweets'
  get 'all_users' => 'epicenter#all_users'
  get "following" => 'epicenter#following'
  get "followers" => 'epicenter#followers'
  resources :tweets
  devise_for :users


  # root 'tweets#index' changed our root to epicenter page
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

# get '/extension' => 'controller#method'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tweet_tags
	has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	belongs_to :user #define association

	has_many :tweet_tags
	has_many :tags, through: :tweet_tags

	  validates :message, presence: true
  validates :message, length: {maximum: 140, 
too_long: "A tweet is only 140 max. Everybody knows that!"} #making sure that tweet param are set
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
	belongs_to :tweet 
	belongs_to :tag 
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :tweets #define association
   
   mount_uploader :avatar, AvatarUploader #carrierwave

 
       validates :username, presence: true, uniqueness: true #email    

       serialize :following, Array #tricking add followers migration into an array   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	# Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    #no coresponding controller so we put this in application controller
    #whitelisting these fields
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location, :avatar])
  end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  before_action :authenticate_user!
  def feed #my tweets and my followers will be loaded and pushed to epicenter feed
  	@tweet = Tweet.new
    @following_tweets = []

    Tweet.all.each do |tweet|
      if current_user.following.include?(tweet.user_id)  || current_user.id == tweet.user_id
        @following_tweets.push(tweet)
      end
    end
  end

  def following
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if @user.following.include?(user.id)
        @users.push(user)
      end  
    end


  end  
# jack diane bob if start with Jack does then put him in users array
# @user the user we want to fpcus on  does Jack follow User?
  
  def followers
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if user.following.include?(@user.id)
      @users.push(user)
      end 
    end
  end  

 def all_users
  @users = User.all
 end 

  def tag_tweets
    @tag = Tag.find(params[:id])  
  end

  def show_user
  	 @user = User.find(params[:id])
  end

  def now_following
	  # We are adding the user.id of the user you want to 
	  # follow to your following array.
	  # and we want to make sure it's saved in there as an integer
	  current_user.following.push(params[:id].to_i)
	  current_user.save

	  redirect_to show_user_path(id: params[:id])
end

  def unfollow
  current_user.following.delete(params[:id].to_i)
  current_user.save

  redirect_to show_user_path(id: params[:id])   
end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user! #making sure they sign up or sign in first
  
  include TweetsHelper
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(tweet_params)

    @tweet = get_tagged(@tweet)


    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper

	def get_tagged(tweet)
		message_arr = tweet.message.split

		message_arr.each_with_index do |word, index|
			if word[0] == "#"
				if Tag.pluck(:phrase).include?(word.downcase)
				#we are not creating a new tag, just using exsisting one think #USA
					tag = Tag.find_by(phrase: word.downcase) 
				else
					tag = Tag.create(phrase: word.downcase)
				end
				tweet_tag = TweetTag.create(tweet_id: tweet.id, tag_id: tag.id)
				message_arr[index] = "<a href='tag_tweets?id=#{tag.id}'>#{word}</a>"
			end
		end

		tweet.message = message_arr.join(" ")
		return tweet
	end	

end

# @tweet.update(message: message_arr.join(" "))

app/views/epicenter/_user_list.html.erb
<div class="row">
	<% @users.each do |user| %>
		<div class="col-md-3">
			<div class="well">
				<div class="row">
					<div class="col-xs-6">
						<%= image_tag user.avatar.url, class: "img-circle", size:100 %>
					</div>
					<div class="col-xs-6">
						<% if current_user.following.include?(user.id) %>
              <%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary", id: "unfollow_btn" %>
            <% else %>
                <% if current_user.id != user.id %>
                <%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
            <% end %>
            <% end %>
					</div>
				</div>
				<%= link_to show_user_path(id: user.id) do %>
					<h3><%= user.name %></h3>
					<p>@<%= user.username %></p>
				<% end %>
				<p><%= user.bio %></p>
			</div>
		</div>
	<% end %>
</div>

app/views/epicenter/all_users.html.erb
<h1>Directory</h1>



<%= render 'user_list' %>

app/views/epicenter/feed.html.erb
<h1>@<%= current_user.username %>'s Twitter Feed</h1>
<p>Here is what your "friends" are saying:</p>



<!-- sidebar begin-- -->
<div class="row"> 
	<div class="col-md-3">
		<div class="panel panel-heading">
			<% if current_user.avatar.blank? == false %>
	            <%= image_tag current_user.avatar.url, size:100, class: "img-circle" %>
	        <% end %> 
	        <h4><%= link_to current_user.name, show_user_path(id: current_user.id) %></h4>
	        <p class="text-muted">@<%= link_to current_user.username, show_user_path(id: current_user.id) %>
		</div> <!-- end panel heading -->


		<div class="panel panel-body">
			<h4>placeholder for trends for you</h4>
			<p>need to add ruby instructions in order to get the trends like twitter has</p>
			<p>maybe add the #blessed and others here? using a "< %  = "</p>
			<p>#USA</p>
			<p>#Soccer Team</p>
			<p>#BEfit</p>
			<p>#Summer</p>
			<p>#Heatwave</p>
			<p>#lebron</p>
		</div>	<!-- end panel body -->
	</div> <!-- end col  -->
	<!-- end sidebar -->


<!-- middle column which is the main one for the tweeter feed -->

	<div class="col-md-6">
		<div class="panel panel-body">
			<%= render 'tweets/form', tweet: @tweet %>
		</div>
		<% @following_tweets.each do |tweet| %>
		<div class="panel panel-body">
			<div class="row">
				<div class="col-xs-2">
				
					<% if tweet.user.avatar.blank? == false %>
		            <%= image_tag current_user.avatar.url, size:25, class: "img-circle" %>
		            <% end %>
		        </div>
				<div class="col-xs-10">
					<p><strong><%= link_to tweet.user.name, show_user_path(id: tweet.user.id)%></strong><span class="text-muted">@<%= link_to tweet.user.username, show_user_path(id: tweet.user.id)%></span></p>
					<p><%= tweet.message.html_safe %></p>
					<p><small><%= time_ago_in_words(tweet.created_at) %></small></p>
				</div>	
			</div>	
		</div>	
		<% end %>
	</div>  <!-- end main feed -->

<!-- begin who to follow sidebar col -->

	<div class="col-md-3">
			<div class="panel panel-body">
					<strong>Who to follow</strong><br>
					<strong>This is place holder text for the info that is going here. Will need to add Ruby intructions
					to get the exact information that is needed. Just want to show how the page should look when it is completed.</strong> 
					<br>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
					<br><strong>More Placeholder</strong>
					<br>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

			</div> <!-- end panel body for who to follow sidebar -->

			<!-- footer for about twitter -->
			<div class="panel panel-footer">
				 Placeholder for links for copywrite, About, help center, terms, etc
				 <strong>however, this might be accomplished with a navbar footer that is
				 responsive based on the type of screen</strong>
			</div>	 


				
	</div>	<!-- end of 'who to follow sidebar col -->

</div> <!-- end of row -->

app/views/epicenter/followers.html.erb
<h1><%= @user.name %>'s Followers </h1>

<%= render 'user_list' %>

app/views/epicenter/following.html.erb
<h1><%= @user.name %> is Following </h1>

<%= render 'user_list' %>

app/views/epicenter/now_following.html.erb
<h1>Epicenter#now_following</h1>
<p>Find me in app/views/epicenter/now_following.html.erb</p>

app/views/epicenter/show_user.html.erb
<div class="row">
    <div class="col-md-12">
        <%= image_tag @user.avatar.url, class: "img-circle", size:100 %>
        <span class="pull-right">
            <% if current_user.following.include?(@user.id) %>
                <%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-primary", id: "unfollow_btn" %>
            <% else %>
                <% if current_user.id != @user.id %>
                <%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
            <% end %>
            <% end %>
        </span>
    </div>

    <div class="col-md-4">
        <h3><%= @user.name %></h3>
        <p>@<%= @user.username %></p>
        <p><%= @user.location %></p>
        <p><%= @user.bio %></p>

          <h1>  <%= link_to 'Back', tweets_path %> <h1>
             <h1> <%= link_to "Followers", followers_path(id: @user.id) %> <h1>
                <h1> <%= link_to "Following", followers_path(id: @user.id) %> <h1>
                
                                                                         

    </div>
    <div class="col-md-8">

        <% @user.tweets.each do |tweet| %>
           <div class="panel panel-body">
            <div class="row">
                <div class="col-xs-2">
                
                    <% if tweet.user.avatar.blank? == false %>
                    <%= image_tag current_user.avatar.url, size:25, class: "img-circle" %>
                    <% end %>
                </div>
                <div class="col-xs-10">
                    <p><strong><%= link_to tweet.user.name, show_user_path(id: tweet.user.id)%></strong><span class="text-muted">@<%= link_to tweet.user.username, show_user_path(id: tweet.user.id)%></span></p>
                    <p><%= tweet.message.html_safe %></p>
                    <p><small><%= time_ago_in_words(tweet.created_at) %></small></p>
                </div>  
            </div>  
        </div>  
        <% end %>
    </div>
</div>

app/views/epicenter/tag_tweets.html.erb
<h1><%= @tag.phrase %></h1>

<!-- different from slides used from feed and made changes to col -->

<div class="row"> 
	<div class="col-md-3">
		<div class="panel panel-body">
			<% if current_user.avatar.blank? == false %>
	            <%= image_tag current_user.avatar.url, size:100, class: "img-circle" %>
	        <% end %> 
	        <h4><%= link_to current_user.name, show_user_path(id: current_user.id) %></h4>
	        <p class="text-muted">@<%= link_to current_user.username, show_user_path(id: current_user.id) %>
		</div>
	</div>  <!-- end sidebar -->


	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-body">
		
		</div>
		<% @tag.tweets.order(created_at: :desc).each do |tweet| %>
			<div class="panel panel-body">
				<div class="row">
					<div class="col-xs-2">
					
						<% if tweet.user.avatar.blank? == false %>
			            <%= image_tag current_user.avatar.url, size:25, class: "img-circle" %>
			      <% end %>
			        </div>
					<div class="col-xs-10">
						<p><strong><%= link_to tweet.user.name, show_user_path(id: tweet.user.id)%></strong><span class="text-muted">@<%= link_to tweet.user.username, show_user_path(id: tweet.user.id)%></span></p>
						<p><%= tweet.message.html_safe %></p>
						<p><small><%= time_ago_in_words(tweet.created_at) %></small></p>
					</div>	
				</div>	
			</div>	
		<% end %>
	</div>  <!-- end main feed -->

</div>

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweeter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <!-- app/views/layouts/application.html.erb -->
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Home", root_path, class: "navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Compose New Tweet", new_tweet_path %></li>
          <!-- added this to show in navbar the tweets page used the path--look at rake -->
          <li><%= link_to "All Users", all_users_path%></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <% if current_user.avatar.blank? == false %>
                  <%= image_tag current_user.avatar.url, size:25  %>
                <% end %> 
                @<%= current_user.username %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_user_registration_path %>
                  
                </li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :message %>
    <%= form.text_field :message, class: "form-control" %>
  </div>

<!-- want the user id to be hidden and the person tweeting is the user  they can't decide who they are tweeting for -->
  <div class="form-group"> 
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="form-group">
    <%= form.submit "Tweet this!", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message.html_safe %></td>

        <td>
          <%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %>
            
       </td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message.html_safe %>
</p>

<!-- changed to username instead of user id that way
it will show the username of the person tweeting -->
<p>
    <strong>User:</strong>
    <%= link_to @tweet.user.username, 
       show_user_path(id: @tweet.user.id) %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>